// ============================================================================
// synapse/hai_frontend_sim.h
// Project Synapse – Cycle-Approximate HAI Hardware Simulator
// ============================================================================
#pragma once

#include <vector>
#include <cstdint>
#include <unordered_map>
#include <iostream>

namespace synapse::sim {

/**
 * @struct SimulationMetrics
 * @brief Telemetry captured during a single simulation run.
 */
struct SimulationMetrics {
    uint64_t total_cycles = 0;
    uint64_t total_bytes_fetched = 0;
    uint32_t delta_updates_processed = 0;
    uint32_t cache_hits = 0;
    uint32_t cache_misses = 0;
    
    float calculate_compression_ratio(uint64_t raw_size) const {
        return static_cast<float>(raw_size) / total_bytes_fetched;
    }
};

/**
 * @class HAIFrontendSim
 * @brief Simulates the hardware logic that interprets HAI bytecode.
 */
class HAIFrontendSim {
public:
    HAIFrontendSim(size_t cache_size_kb) : cache_capacity_(cache_size_kb * 1024) {}

    /**
     * @brief Interprets a bytecode stream and simulates hardware expansion.
     * @param stream The raw HAI bytecode generated by the UMD.
     */
    void simulate_batch(const std::vector<uint8_t>& stream, SimulationMetrics& metrics) {
        size_t pc = 0; // Program Counter

        // 1. Header Fetch (32 Bytes)
        if (stream.size() < 32) return;
        metrics.total_bytes_fetched += 32;
        metrics.total_cycles += 4; // Constant latency for header parse
        pc += 32;

        while (pc < stream.size()) {
            uint16_t descriptor = *reinterpret_cast<const uint16_t*>(&stream[pc]);
            uint8_t opcode = descriptor & 0x3F;
            uint8_t length = (descriptor >> 6) & 0x0F;
            
            pc += 2;
            metrics.total_bytes_fetched += 2;

            if (opcode == 0xFF) { // DELTA_UPDATE logic
                handle_delta_update(stream, pc, metrics);
            } else if (opcode == 0x30) { // REPEAT logic
                handle_repeat(stream, pc, metrics);
            } else {
                handle_standard_opcode(opcode, length, stream, pc, metrics);
            }
        }
    }

private:
    void handle_delta_update(const std::vector<uint8_t>& stream, size_t& pc, SimulationMetrics& metrics) {
        uint8_t target_op = stream[pc++];
        uint16_t mask = *reinterpret_cast<const uint16_t*>(&stream[pc]);
        pc += 2;

        metrics.total_bytes_fetched += 3;
        metrics.delta_updates_processed++;
        
        // Count bits set in mask to determine payload length
        #ifdef _MSC_VER
        int fields_to_update = __popcnt(mask);
        #else
        int fields_to_update = __builtin_popcount(mask);
        #endif
        size_t payload_size = fields_to_update * 4;
        
        // Simulation: Merging fields into Shadow State
        // In real hardware, this is a parallel mux operation.
        metrics.total_bytes_fetched += payload_size;
        metrics.total_cycles += 2; // Fixed cycle cost for SSR merge
        
        pc += payload_size;
    }

    void handle_standard_opcode(uint8_t op, uint8_t len, const std::vector<uint8_t>& stream, size_t& pc, SimulationMetrics& metrics) {
        size_t payload_size = len * 4;
        
        // Update Shadow State for future Delta Updates
        shadow_registers_[op] = std::vector<uint8_t>(stream.begin() + pc, stream.begin() + pc + payload_size);
        
        metrics.total_bytes_fetched += payload_size;
        metrics.total_cycles += 1; // Standard dispatch cycle
        pc += payload_size;
    }

    void handle_repeat(const std::vector<uint8_t>& stream, size_t& pc, SimulationMetrics& metrics) {
        uint32_t count = *reinterpret_cast<const uint32_t*>(&stream[pc]);
        pc += 4;
        
        metrics.total_bytes_fetched += 4;
        // REPEAT is ultra-efficient: 1 cycle per expanded draw
        metrics.total_cycles += count; 
    }

    // Shadow Register File: Opcode -> Last Payload
    std::unordered_map<uint8_t, std::vector<uint8_t>> shadow_registers_;
    size_t cache_capacity_;
};

} // namespace synapse::sim