#ifndef SYNAPSE_IGPU_ML_H
#define SYNAPSE_IGPU_ML_H
/* GENERATED BY cbindgen - do not edit */

#include <stdint.h>
#include <stddef.h>

typedef struct SynapseFeatureVector {
    float shader_complexity_norm;
    float vertex_count_log_norm;
    float draw_call_rate_norm;
    float cache_hit_rate;
    float dvfs_headroom;
    float thermal_headroom;
    float predictor_accuracy;
    float is_compute_dispatch;
} SynapseFeatureVector;

typedef struct SynapseExperience {
    SynapseFeatureVector features;
    uint32_t action;
    float reward;
    uint64_t timestamp_ns;
    uint64_t session_id;
    float energy_joules;
    uint32_t thermal_events;
    float confidence;
} SynapseExperience;

typedef struct SynapseActionScores {
    float scores[3];
    uint32_t chosen;
    float confidence;
    int epsilon_greedy;
} SynapseActionScores;

typedef struct SynapseModelExplanation {
    float feature_importances[8];
    float predicted_scores[3];
    float confidence;
    const char* model_version;
    const char* notes;
} SynapseModelExplanation;

typedef struct SynapseUpdateResult {
    float loss;
    float gradient_norm;
    float learning_rate;
} SynapseUpdateResult;

typedef struct SynapseBatchResult {
    float avg_loss;
    size_t samples;
    uint64_t duration_us;
} SynapseBatchResult;

#endif /* SYNAPSE_IGPU_ML_H */
